### ISSUE TITLE
ajouter du contexte

### ISSUE THREAD

**Issue by ipante** [MAROUA2022/Projet-VDD-MJEMAI-2022#2]
L'analyse proposée dans votre README est très intéressante et gagnerait à apparaître (en plus du README) en différents endroits de votre visualisation afin d'aider le lectorat à comprendre ce qu'il regarde.

Injectez partie du texte de votre README au sein de vos pages.

**Comment by MAROUA2022** [comment]
Bonjour Monsieur, 
Merci pour votre message, la mise à jour a été faite. 
Bon début de soirée.
